# Generated by Django 4.2.3 on 2023-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_dasignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasignation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emp_category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
