# Generated by Django 4.2.3 on 2023-12-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_dasignation_is_active_emp_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_father_name', models.CharField(blank=True, max_length=100)),
                ('emp_dob', models.DateField(blank=True, max_length=20)),
                ('emp_mobile_no', models.CharField(blank=True, max_length=20)),
                ('emp_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('emp_permante_address', models.CharField(blank=True, max_length=300)),
                ('emp_permante_state', models.TextField(blank=True, max_length=100)),
                ('emp_local_address', models.CharField(blank=True, max_length=300)),
                ('emp_addhar_no', models.CharField(blank=True, max_length=15)),
                ('emp_bank_ifsc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_bank_ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_pf_no', models.CharField(blank=True, max_length=100)),
                ('emp_esi_no', models.CharField(blank=True, max_length=100)),
                ('emp_salary_ctc', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.bank')),
                ('emp_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.emp_category')),
                ('emp_work_location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.emp_work_location')),
                ('emp_zone_loation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.emp_zone_location')),
            ],
        ),
    ]
