# Generated by Django 4.2.3 on 2024-01-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_employee_aadhar_file_employee_bank_passbook_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_designation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.dasignation'),
        ),
    ]
