# Generated by Django 4.2.3 on 2024-01-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_alter_employee_emp_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.bank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.emp_category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_designation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.dasignation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_work_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.emp_work_location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_zone_loation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.emp_zone_location'),
        ),
    ]
